### ISSUE TITLE
Question about Vue components, Vuex and Vue Axios

### ISSUE THREAD

**Issue by thasorn** [it-kmitl-2018/group8-frontend#39]
สวัสดีครับ วันนี้ผมมีเรื่องอยากรบกวนพี่ @pangaunn อีกครั้งหนึ่งครับ ตอนนี้ทาง Frontend กำลังประสบกับปัญหาการแบ่ง Form แต่ละส่วนเป็น Component ย่อย ๆ และการเชื่อมต่อกับส่วน Backend ครับ

ผมได้ศึกษาและทดลองใช้ props และ eventbus ตามคำแนะนำแล้วครับ แต่ทางผมมีเรื่องรบกวนสอบถามและคำแนะนำสำหรับการนำไปใช้ในโปรเจคครับ

ผมจึงรบกวนสอบถามพี่ @pangaunn ว่าหากทางผมจะนัดพูดคุยและปรึกษาผ่าน Skype อีกครั้ง ไม่ทราบว่าจะสะดวกช่วงวันที่เท่าใดและช่วงเวลาใดบ้างครับ

ขอบขอบพระคุณสำหรับคำตอบล่วงหน้าและขออภัยหากเป็นการรบกวนจนเกินไปครับ

ขอบพระคุณครับ

**Comment by pangaunn** [comment]
อาทิตย์นี้วันธรรมดาไม่ว่างเลยครับ คงต้องวันเสาร์เป็นต้นไปครับนัดวัน-เวลามาได้เลยครับ

**Comment by thasorn** [comment]
@pangaunn ถ้าอย่างนั้น รบกวนเป็นวันเสาร์ที่ 17 มีนาคม เวลา 20.00 น. ไม่ทราบว่าสะดวกไหมครับ

**Comment by pangaunn** [comment]
ได้ครับ วันเสาร์นี้ 20.00 นะ
