### ISSUE TITLE
Permission for Travis-CI

### ISSUE THREAD

**Issue by thasorn** [it-kmitl-2018/group8-frontend#46]
รบกวนสอบถามเกี่ยวกับการติดตั้ง Travis-CI ใน repository ครับ
ทางผมได้ลองสมัครสมาชิกใน travis-ci.org แล้ว และตาม Tutorial ที่ระบุบนเว็บไซต์ได้บอกขั้นตอนแรกให้ทำการ switch on สำหรับ repository นั้น ๆ แต่ว่า repository ของกลุ่มผมถูก lock เอาไว้และต้องใช้ permission จาก admin ดังภาพด้านล่างครับ

หน้าสำหรับ switch on

![image](https://user-images.githubusercontent.com/15757535/37861493-81610a28-2f6d-11e8-93c8-369f1fe267a9.png)

หน้าระบุว่าจำเป็นต้องใช้ permission

![image](https://user-images.githubusercontent.com/15757535/37861497-935f93c0-2f6d-11e8-9de1-20ba12dcd155.png)

จึงรบกวนสอบถามว่าตรงส่วนนี้เกิดจากความเข้าใจผิดของทางผมหรือจำเป็นต้องของ permission จากทางพี่ก่อนครับ

ขอบคุณสำหรับคำตอบล่วงหน้าครับ

**Comment by champillon** [comment]
granted ให้เป็น admin ละ ลุยเองโลดดดดด
