### ISSUE TITLE
Configuration in .travis.yml file

### ISSUE THREAD

**Issue by thasorn** [it-kmitl-2018/group8-frontend#48]
@pangaunn @champillon 

วันนี้มีเรื่องรบกวนสอบถามเกี่ยวกับการ config และ setting ใน .travis.yml ครับ

จาก PR ที่ได้เสนอไป ([See here](https://github.com/it-kmitl-2018/group8-frontend/pull/47)) ทำให้ทราบว่ามีข้อผิดพลาดบางอย่างเกิดขึ้น

ทางผมได้ทดลองลบไฟล์ test ที่ไม่ใช้และปรับค่าในไฟล์บางอย่างแล้ว แต่ปัญหานี้ดูเหมือนจะยังไม่หายไป

จึงรบกวนสอบถามพี่ ๆ ถึงขั้นตอนการ Config และ Setting ค่าที่ถูกต้องสำหรับไฟล์ .travis.yml นี้ด้วยครับ

ขอบพระคุณสำหรับคำตอบล่วงหน้าครับ

**Comment by champillon** [comment]
น่าจะเป็นตรงนี้นะ

npm run dist ในเครื่องได้มั้ย?

<img width="621" alt="screen shot 2561-03-26 at 10 24 18" src="https://user-images.githubusercontent.com/1620789/37885520-ecb38878-30df-11e8-8a21-98e3d2f6c3d3.png">

**Comment by thasorn** [comment]
npm run dist เกิด error missing script ครับ

**Comment by champillon** [comment]
ใช่ๆ มันพังตรงนี้แหละ ลองดูซิว่าจะแก้ยังไง
